version: '3.8'

networks:
  lgtm-net:
    driver: bridge

volumes:
  prometheus_data: {} 


services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
      - /root/test_gstreamer_debug:/root/test_gstreamer_debug
    networks:
      - lgtm-net
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: ["-config.file=/etc/loki/loki.yml"]
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/etc/loki
    networks:
      - lgtm-net
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: ["-config.file=/etc/promtail/promtail.yml"]
    ports: 
      - "9080:9080"
    volumes:
      - ./promtail:/etc/promtail
      - /root/ai-agent-service/ai-agent-service/logs:/root/ai-agent-service/ai-agent-service/logs
      - /root/test_gstreamer_debug:/root/test_gstreamer_debug
      - /root/process-monitor:/root/process-monitor
      - /root/aios-checking-stream-quality-services/csvs:/root/aios-checking-stream-quality-services/csvs
    networks:
      - lgtm-net
    restart: unless-stopped

  process_exporter:
    image: ncabatoff/process-exporter:latest
    container_name: process_exporter
    command:
      - '-config.path=/config/config.yml'
      - '-procfs=/host/proc'
    pid: host
    ports:
      - "9256:9256"
    volumes:
      - ./process-exporter:/config
      - /proc:/host/proc:ro    
    networks:
      - lgtm-net
    restart: unless-stopped
