process_names:
  - name: 'ppl_detection_double_check-stream{{.Matches.stream_id}}'
    comm:
      - uvicorn
      - python3.9
    cmdline:
      - '.*uvicorn\s+ppl_detection_double_check_stream(?P<stream_id>\d+).*'

  - name: 'checkdoor_ai_agent-stream{{.Matches.stream_id}}'
    comm:
      - uvicorn
      - python3.9
    cmdline:
      - '.*uvicorn\s+checkdoor_ai_agent_stream(?P<stream_id>\d+).*'