global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'process_exporter'
    static_configs:
      - targets: ['process_exporter:9256']

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']